apiVersion: v2
appVersion: 1.33.0
dependencies:
- name: harness-common
  repository: https://harness.github.io/helm-common
  version: 1.x.x
description: A Helm chart for Kubernetes
name: chaos-k8s-ifs
type: application
version: 1.57.3
