{{- if eq (include "harnesscommon.secrets.hasESOSecrets" (dict "secretsCtx" .Values.redis.secrets)) "true" }}
    {{- $localESOSecretIdentifier := (include "harnesscommon.secrets.localESOSecretCtxIdentifier" (dict "ctx" $ "additionalCtxIdentifier" "redis")) }}
    {{- include "harnesscommon.secrets.generateExternalSecret" (dict "secretsCtx" .Values.redis.secrets "secretNamePrefix" $localESOSecretIdentifier) }}
    {{- print "\n---" }}
{{- end }}
{{- if eq (include "harnesscommon.secrets.hasESOSecrets" (dict "secretsCtx" .Values.timescaledb.secrets)) "true" }}
    {{- $localESOSecretIdentifier := (include "harnesscommon.secrets.localESOSecretCtxIdentifier" (dict "ctx" $ "additionalCtxIdentifier" "timescaledb")) }}
    {{- include "harnesscommon.secrets.generateExternalSecret" (dict "secretsCtx" .Values.timescaledb.secrets "secretNamePrefix" $localESOSecretIdentifier) }}
    {{- print "\n---" }}
{{- end }}
