{{- if eq (include "harnesscommon.secrets.hasESOSecrets" (dict "secretsCtx" .Values.secrets)) "true" }}
    {{- $localESOSecretIdentifier := (include "harnesscommon.secrets.localESOSecretCtxIdentifier" (dict "ctx" $ )) }}
    {{ include "harnesscommon.secrets.generateExternalSecret" (dict "secretsCtx" .Values.secrets "secretNamePrefix" $localESOSecretIdentifier) }}
    {{- print "\n---" }}
{{- end }}
{{- if eq (include "harnesscommon.secrets.hasESOSecrets" (dict "secretsCtx" .Values.timescaledb.secrets)) "true" }}
    {{- $localESOSecretIdentifier := (include "harnesscommon.secrets.localESOSecretCtxIdentifier" (dict "ctx" $ "additionalCtxIdentifier" "timescaledb")) }}
    {{- include "harnesscommon.secrets.generateExternalSecret" (dict "secretsCtx" .Values.timescaledb.secrets "secretNamePrefix" $localESOSecretIdentifier) }}
    {{- print "\n---" }}
{{- end }}
{{- if eq (include "harnesscommon.secrets.hasESOSecrets" (dict "secretsCtx" .Values.secondaryTimescaledb.secrets)) "true" }}
    {{- $localESOSecretIdentifier := (include "harnesscommon.secrets.localESOSecretCtxIdentifier" (dict "ctx" $ "additionalCtxIdentifier" "secondary-timescaledb")) }}
    {{- include "harnesscommon.secrets.generateExternalSecret" (dict "secretsCtx" .Values.secondaryTimescaledb.secrets "secretNamePrefix" $localESOSecretIdentifier) }}
    {{- print "\n---" }}
{{- end }}
{{- include "harnesscommon.dbv3.generateLocalMongoExternalSecret" (dict "ctx" $) }}
{{- if eq (include "harnesscommon.secrets.hasESOSecrets" (dict "secretsCtx" .Values.postgres.secrets)) "true" }}
    {{- $localESOSecretIdentifier := (include "harnesscommon.secrets.localESOSecretCtxIdentifier" (dict "ctx" $ "additionalCtxIdentifier" "postgres")) }}
    {{- include "harnesscommon.secrets.generateExternalSecret" (dict "secretsCtx" .Values.postgres.secrets "secretNamePrefix" $localESOSecretIdentifier) }}
    {{- print "\n---" }}
{{- end }}