apiVersion: v2
appVersion: 1.773.0
dependencies:
- name: harness-common
  repository: https://harness.github.io/helm-common
  version: 1.x.x
description: A Helm chart for Kubernetes
name: code-githa
type: application
version: 1.34.0
