apiVersion: v1
kind: Secret
metadata:
  name: {{ include "codesearch.name" . }}
  namespace: {{ .Release.Namespace }}
data:
{{- include "harnesscommon.generateSecretsInHelpers" (dict "ctx" $) | indent 2}}

{{- if .Values.dockercfg }}
---
apiVersion: v1
kind: Secret
metadata:
  name:  {{ include "codesearch.name" . }}-dockercfg
  namespace: {{ .Release.Namespace }}
  annotations:
    harness.io/skip-versioning: true
type: kubernetes.io/dockercfg
data:
  .dockercfg: {{ .Values.dockercfg | quote }}
{{- end }}
